version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pieter12
      POSTGRES_DB: image-generator
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  nextjs:
    image: mertcant18/aiconcraft:latest
    ports:
      - "3000:3000"
    environment:
      - API_KEY=lmwr_sk_0petDyN70v_1qzSOXkcWksba59peGWzp4zWVjh2B9SZtnTze
      - USER=postgres
      - HOST=postgres  # Updated to use the service name
      - DATABASE=image-generator
      - PASSWORD=pieter12
      - DB_PORT=5432
    depends_on:
      - postgres

volumes:
  postgres_data:
